version: "3.7"

services:
    thingsboard:
        image: ivan28823/thingsboard:2.4.3-slim-buster
        ports:
            - 9090:9090
            - 1883:1883
            - 5683:5683/udp
        environment:
            - LOAD_DEMO=false
            - LOW_RAM_USAGE=true
            - PG_HOST=db-postgres
            - PG_USER=thingsboard
            - PG_PASS=verysecret
        volumes:
            - thingsboard-data:/data
    
    db-postgres:
        image: postgres:12-alpine
        environment:
            - POSTGRES_USER=thingsboard
            - POSTGRES_DB=thingsboard 
            - POSTGRES_PASSWORD=verysecret
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
    thingsboard-data:
